# Generated by Django 3.2 on 2024-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='键')),
                ('value', models.CharField(default=None, max_length=100, verbose_name='值')),
                ('label', models.CharField(default=None, max_length=50, null=True, verbose_name='显示')),
                ('placeholder', models.CharField(max_length=50, verbose_name='输入提示')),
                ('is_show_value', models.IntegerField(default=1, null=True, verbose_name='对外显示值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '系统配置',
                'db_table': 'tb_system',
                'ordering': ('-id',),
            },
        ),
    ]
