# Generated by Django 3.2 on 2024-10-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0001_initial'),
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertTrusteeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, unique=True, verbose_name='域名名称')),
                ('ssl_cert', models.TextField(default=None, null=True, verbose_name='SSL证书')),
                ('ssl_cert_key', models.TextField(default=None, null=True, verbose_name='SSL证书私钥')),
                ('ssl_start_time', models.DateTimeField(default=None, null=True, verbose_name='SSL签发时间')),
                ('ssl_expire_time', models.DateTimeField(default=None, null=True, verbose_name='SSL过期时间')),
                ('remaining_days', models.IntegerField(default=0, null=True, verbose_name='剩余天数')),
                ('total_days', models.IntegerField(default=0, null=True, verbose_name='总共天数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('envs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.envs', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '托管证书',
                'db_table': 'tb_cert_trusteeship',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CertTrusteeshipDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_type_id', models.IntegerField(default=0, null=True, verbose_name='部署方式')),
                ('deploy_key_file', models.CharField(default=None, max_length=50, null=True, verbose_name='key部署路径')),
                ('deploy_fullchain_file', models.CharField(default=None, max_length=50, null=True, verbose_name='pem部署路径')),
                ('deploy_reloadcmd', models.CharField(default=None, max_length=50, null=True, verbose_name='重启命令')),
                ('status', models.IntegerField(default=0, null=True, verbose_name='部署状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('cert_trusteeship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cert_trusteeship_row', to='certs.certtrusteeship', verbose_name='托管证书')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hosts.host', verbose_name='部署主机')),
            ],
            options={
                'verbose_name_plural': '托管证书部署',
                'db_table': 'tb_cert_trusteeship_deploy',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, unique=True, verbose_name='域名名称')),
                ('ips_count', models.IntegerField(default=0, null=True, verbose_name='主机数量')),
                ('root_domain', models.CharField(blank=True, max_length=30, null=True, verbose_name='顶级域名')),
                ('port', models.IntegerField(default=443, verbose_name='端口')),
                ('status', models.CharField(choices=[('verified', '已验证'), ('unverified', '未验证')], default='unverified', max_length=10, verbose_name='连接状态')),
                ('issue_time', models.DateTimeField(blank=True, null=True, verbose_name='签发时间')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('remaining_days', models.IntegerField(default=0, null=True, verbose_name='剩余天数')),
                ('total_days', models.IntegerField(default=0, null=True, verbose_name='总共天数')),
                ('is_monitor', models.IntegerField(default=1, verbose_name='是否监测')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('ssl_type', models.IntegerField(default=0, verbose_name='加密方式')),
                ('auto_update', models.IntegerField(default=1, verbose_name='自动更新')),
                ('expire_notify', models.IntegerField(default=0, verbose_name='到期提醒')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('envs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.envs', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '域名证书',
                'db_table': 'tb_certs',
                'ordering': ('-id',),
            },
        ),
    ]
