# Generated by Django 3.2 on 2024-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default=None, max_length=30, null=True, unique=True, verbose_name='远程主机')),
                ('port', models.IntegerField(default=22, null=True, verbose_name='远程端口')),
                ('username', models.CharField(default=None, max_length=30, null=True, verbose_name='远程用户')),
                ('auth_type', models.IntegerField(default=0, verbose_name='验证方式')),
                ('password', models.TextField(blank=True, null=True, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='密钥')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '证书部署主机',
                'db_table': 'tb_host',
                'ordering': ('-id',),
            },
        ),
    ]
