# Generated by Django 3.2 on 2024-10-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='监测名称')),
                ('monitor_type', models.IntegerField(default=1, verbose_name='监测类型')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方式')),
                ('url', models.CharField(default=None, max_length=100, verbose_name='请求URL')),
                ('timeout', models.IntegerField(default=3, verbose_name='请求超时')),
                ('interval', models.IntegerField(default=60, verbose_name='检测频率')),
                ('retries', models.IntegerField(default=0, verbose_name='重试次数')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否监测')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('envs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.envs', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '监控任务',
                'db_table': 'tb_monitor',
                'ordering': ('-id',),
            },
        ),
    ]
