# Generated by Django 3.2 on 2024-10-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.IntegerField(default=0, verbose_name='监控ID')),
                ('monitor_type', models.IntegerField(default=0, verbose_name='监控类型')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('result', models.TextField(default=None, null=True, verbose_name='结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '监控日志',
                'db_table': 'tb_log_monitor',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LogScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('error_message', models.TextField(default=None, null=True, verbose_name='执行结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '日志',
                'db_table': 'tb_log_scheduler',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LogOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(default=None, max_length=30, null=True, verbose_name='操作表')),
                ('type_id', models.IntegerField(default=0, verbose_name='操作类型ID')),
                ('before', models.TextField(default=None, null=True, verbose_name='操作之前')),
                ('after', models.TextField(default=None, null=True, verbose_name='操作之前')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '操作日志',
                'db_table': 'tb_log_operation',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(default=None, null=True, verbose_name='任务名称')),
                ('function_name', models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='函数名')),
                ('status', models.BooleanField(default=None, null=True, verbose_name='执行状态')),
                ('result', models.TextField(default=None, null=True, verbose_name='执行结果')),
                ('start_time', models.DateTimeField(default=None, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=None, null=True, verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('envs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envs.envs', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '异步任务执行情况记录',
                'db_table': 'tb_log_async_task',
                'ordering': ('-id',),
            },
        ),
    ]
