# Generated by Django 3.2 on 2024-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.CharField(max_length=50, unique=True, verbose_name='域名列表')),
                ('ssl_cert', models.TextField(default=None, null=True, verbose_name='SSL证书')),
                ('ssl_cert_key', models.TextField(default=None, null=True, verbose_name='SSL证书私钥')),
                ('ssl_start_time', models.DateTimeField(default=None, null=True, verbose_name='SSL签发时间')),
                ('ssl_expire_time', models.DateTimeField(default=None, null=True, verbose_name='SSL过期时间')),
                ('directory_type', models.CharField(default='letsencrypt', max_length=30, null=True, verbose_name='证书提供商')),
                ('key_type', models.CharField(default='RSA', max_length=30, null=True, verbose_name='加密方式')),
                ('challenge_type', models.CharField(default='http-01', max_length=30, null=True, verbose_name='域名验证类型')),
                ('challenge_deploy_type_id', models.IntegerField(default=0, verbose_name='验证文件部署方式')),
                ('challenge_deploy_host_id', models.IntegerField(default=0, null=True, verbose_name='验证文件部署主机id')),
                ('challenge_deploy_status', models.IntegerField(default=0, verbose_name='验证文件部署状态')),
                ('challenge_deploy_verify_path', models.CharField(default=None, max_length=50, null=True, verbose_name='验证文件部署目录')),
                ('token', models.CharField(default=None, max_length=100, null=True, verbose_name='域名验证token')),
                ('validation', models.CharField(default=None, max_length=100, null=True, verbose_name='域名验证数据')),
                ('challenge_deploy_dns_id', models.IntegerField(default=0, null=True, verbose_name='验证dns记录id')),
                ('status', models.CharField(default='pending', max_length=100, null=True, verbose_name='验证状态')),
                ('deploy_type_id', models.IntegerField(default=0, null=True, verbose_name='部署方式')),
                ('deploy_host_id', models.IntegerField(default=0, verbose_name='部署主机')),
                ('deploy_header_raw', models.TextField(default=None, null=True, verbose_name='部署请求头')),
                ('deploy_params_raw', models.TextField(default=None, null=True, verbose_name='部署参数')),
                ('deploy_key_file', models.CharField(default=None, max_length=50, null=True, verbose_name='key部署路径')),
                ('deploy_fullchain_file', models.CharField(default=None, max_length=50, null=True, verbose_name='pem部署路径')),
                ('deploy_reloadcmd', models.CharField(default=None, max_length=50, null=True, verbose_name='部署重启命令')),
                ('deploy_url', models.CharField(default=None, max_length=100, null=True, verbose_name='部署请求url')),
                ('deploy_status', models.IntegerField(default=0, null=True, verbose_name='证书部署状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_auto_renew', models.IntegerField(default=0, verbose_name='自动续期')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '申请证书',
                'db_table': 'tb_apply_certs',
                'ordering': ('-id',),
            },
        ),
    ]
