# Generated by Django 3.2 on 2024-10-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_type', models.IntegerField(default=1, verbose_name='DNS类型')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('access_id', models.CharField(default=None, max_length=100, verbose_name='Access ID')),
                ('access_secret', models.CharField(default=None, max_length=100, verbose_name='Access Secret')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': 'DNS账号',
                'db_table': 'tb_dns',
                'ordering': ('-id',),
            },
        ),
    ]
