# Generated by Django 3.2 on 2024-10-27 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('event_id', models.IntegerField(choices=[(1, 'SSL证书到期'), (2, '托管证书到期'), (3, '网站监控系统'), (4, '监控异常恢复')], default=1, verbose_name='事件类型')),
                ('expire_days', models.IntegerField(default=3, verbose_name='过期剩余天数')),
                ('value_raw', models.TextField(default=None, null=True, verbose_name='原始值')),
                ('notify_choice', models.IntegerField(choices=[(1, 'Email'), (2, 'WeChat'), (3, 'DingTalk'), (4, 'WebHook')], default=1, verbose_name='通知方式')),
                ('status', models.IntegerField(default=1, verbose_name='启用状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('envs', models.ManyToManyField(to='envs.Envs', verbose_name='分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '通知配置',
                'db_table': 'tb_notify',
                'ordering': ('-id',),
            },
        ),
    ]
